### ISSUE TITLE
Error when attempting any query

### ISSUE THREAD

**Issue by FuzzOli87** [AndreaOrru/fzf-mopidy-spotify.vim#1]
Hello, I'm getting some errors when I try to do any of the commands on Neovim.
I have fzf, fzf.vim installed.

```
unknown function fzf#wrap
```

**Comment by AndreaOrru** [comment]
https://github.com/junegunn/fzf.vim/issues/210

**Comment by FuzzOli87** [comment]
Wow. I can't believe that was it. I could of sworn that when I install a plugin it got the latest version.

**Comment by AndreaOrru** [comment]
;)
